[project]
name = 'decentralized-portolio'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.decentralized-portolio]
path = 'contracts/decentralized-portolio.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
